### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by FishHave** [SPGoding/datapack-language-server#2039]
Output as below:

```text
TypeError: n.isSubsetOf is not a function
    at EventEmitter.<anonymous> (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:148:31639)
    at EventEmitter.emit (node:events:526:35)
    at e.emit (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:63:46054)
    at EventEmitter.<anonymous> (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:63:46890)
    at EventEmitter.emit (node:events:514:28)
    at e.emit (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:63:17505)
    at e.onEditorConfigurationUpdate (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:63:17594)
    at async e.onEditorConfigurationUpdate (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:63:57515)
    at async OF (c:\Users\Administrator\.vscode\extensions\spgoding.datapack-language-server-4.8.1\dist\server.js:150:193)

Node.js v18.17.1
[Error - 5:46:37 PM] Server process exited with code 1.
[Error - 5:46:37 PM] The Spyglass Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Interestingly, DHP worked well in the version of 4.6.0 and below

**Comment by SPGoding** [comment]
What's your VS Code version? Can you upgrade it?
